name: check-pirc

on:
  workflow_call:
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - 'main'
      - 'dev'
    paths-ignore:
      - '.githooks/**'
      - '**/LICENSE'
      - '**/*.md'

  push:
    branches:
      - 'main'
      - 'dev'
    paths-ignore:
      - '.githooks/**'
      - '**/LICENSE'
      - '**/*.md'

permissions: read-all

jobs:
  lint-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.1

      - name: Format code
        run: |
          opam install ocamlformat=0.28.1
          echo "Running fmt 1"
          opam exec -- dune build @fmt --auto-promote || true
          # We use "|| true" here to suppress the exit code 1 that @fmt throws when it has to
          # reformat code.
          echo "Running fmt 2"
          opam exec -- dune build @fmt
          echo "done"
          # We run @fmt a second time in case it throws a real error. If the first @fmt
          # reformatted without issue, the second @fmt will exit with code 0.

      - name: Commit and push formatted code
        run: |
          CHANGES=$(git diff --diff-filter M)
          if [[ -n $CHANGES ]] ;
          then
            echo "CURRENT BRANCH IS"
            BRANCH=$(git branch --show-current)
            echo $BRANCH
            AUTHOR=$(git log -n 1 --pretty=format:"%an")
            echo $AUTHOR
            EMAIL=$(git log -n 1 --pretty=format:"%ae")
            echo $EMAIL
            COMMIT_MSG=$(git log -n 1 --pretty=format"%B")
            echo $COMMIT_MSG
            git config --global user.name $AUTHOR
            git config --global user.email $EMAIL
            echo "configs set"
            git add -u
            echo "added files"
            git commit -m "$COMMIT_MSG (formatted)"
            echo "committed"
            git push
            echo "pushed"
          fi

  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.1

      - name: Install dependencies
        run: opam install . --deps-only --with-test --with-doc

      - name: Build
        run: opam exec -- dune build
      - name: Build Docs
        run: opam exec -- dune build @doc
        
  Run-Test-Suite:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.1

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build

      - name: Run Tests
        run: |
          TEST_OUTPUT=$(opam exec -- dune test)
          SUMMARY_LINE=$($TEST_OUTPUT tail -n 1)
          if [[ SUMMARY_LINE == FAILED*]] ;
          then
            echo $TEST_OUTPUT
            exit 1
          fi
