name: check-pirc

on:
  workflow_call:
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - 'main'
      - 'dev'
    paths-ignore:
      - '.githooks/**'
      - '**/LICENSE'
      - '**/*.md'

  push:
    branches:
      - 'main'
      - 'dev'
    paths-ignore:
      - '.githooks/**'
      - '**/LICENSE'
      - '**/*.md'

permissions: read-all

jobs:
  lint-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.1

      - name: Format code
        run: |
          opam install ocamlformat=0.28.1
          opam exec -- dune build @fmt --auto-promote

      - name: Commit and push formatted code
        run: |
          AUTHOR=$(git log -n 1 --pretty=format:"%an")
          EMAIL=$(git log -n 1 --pretty=format:"%ae")
          COMMIT_MSG=$(git log -n 1 --pretty=format"%B")
          git config --global user.name $AUTHOR
          git config --global user.email $EMAIL
          git add .
          git commit -m "$COMMIT_MSG (formatted)"
          git push

  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.1

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build

